<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'description' => 'Smartphone flagship Apple dengan teknologi terdepan, kamera profesional, dan performa tinggi.',
                'price' => 18999000,
                'stock' => 15,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'description' => 'Smartphone Android premium dengan S Pen, kamera zoom 100x, dan layar Dynamic AMOLED.',
                'price' => 17999000,
                'stock' => 12,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'MacBook Pro M3',
                'slug' => 'macbook-pro-m3',
                'description' => 'Laptop profesional Apple dengan chip M3, performa luar biasa untuk kreator dan developer.',
                'price' => 24999000,
                'stock' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sony WH-1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'description' => 'Headphone wireless premium dengan noise cancelling terbaik di kelasnya.',
                'price' => 4999000,
                'stock' => 25,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dell XPS 13',
                'slug' => 'dell-xps-13',
                'description' => 'Ultrabook premium dengan desain tipis, layar InfinityEdge, dan performa tinggi.',
                'price' => 19999000,
                'stock' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'iPad Pro 12.9 M2',
                'slug' => 'ipad-pro-12-9-m2',
                'description' => 'Tablet profesional dengan chip M2, Apple Pencil support, dan layar Liquid Retina XDR.',
                'price' => 15999000,
                'stock' => 18,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Apple Watch Series 9',
                'slug' => 'apple-watch-series-9',
                'description' => 'Smartwatch dengan fitur kesehatan lengkap, GPS, dan ekosistem Apple yang terintegrasi.',
                'price' => 5999000,
                'stock' => 30,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Nintendo Switch OLED',
                'slug' => 'nintendo-switch-oled',
                'description' => 'Gaming console hybrid dengan layar OLED 7 inci, bisa dimainkan portable atau di TV.',
                'price' => 4799000,
                'stock' => 20,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Canon EOS R5',
                'slug' => 'canon-eos-r5',
                'description' => 'Kamera mirrorless profesional dengan sensor 45MP, video 8K, dan stabilizer in-body.',
                'price' => 52999000,
                'stock' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'AirPods Pro 2',
                'slug' => 'airpods-pro-2',
                'description' => 'Earbuds premium dengan Active Noise Cancellation, Spatial Audio, dan chip H2.',
                'price' => 3799000,
                'stock' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samsung 55" Neo QLED 8K',
                'slug' => 'samsung-55-neo-qled-8k',
                'description' => 'Smart TV premium dengan resolusi 8K, teknologi Neo QLED, dan AI upscaling.',
                'price' => 32999000,
                'stock' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'PlayStation 5',
                'slug' => 'playstation-5',
                'description' => 'Gaming console next-gen dengan SSD ultra cepat, ray tracing, dan DualSense controller.',
                'price' => 7999000,
                'stock' => 14,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Microsoft Surface Pro 9',
                'slug' => 'microsoft-surface-pro-9',
                'description' => '2-in-1 tablet laptop dengan Windows 11, Intel Core i7, dan Surface Pen support.',
                'price' => 16999000,
                'stock' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'description' => 'Smartphone Android murni dengan AI photography, Magic Eraser, dan update 7 tahun.',
                'price' => 14999000,
                'stock' => 16,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'ASUS ROG Strix G15',
                'slug' => 'asus-rog-strix-g15',
                'description' => 'Gaming laptop dengan RTX 4060, AMD Ryzen 7, dan refresh rate 144Hz untuk gaming optimal.',
                'price' => 22999000,
                'stock' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kindle Oasis',
                'slug' => 'kindle-oasis',
                'description' => 'E-reader premium dengan layar 7 inci, pencahayaan adaptif, dan tahan air IPX8.',
                'price' => 4299000,
                'stock' => 22,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'DJI Mini 4 Pro',
                'slug' => 'dji-mini-4-pro',
                'description' => 'Drone compact dengan kamera 4K/60fps, obstacle sensing, dan waktu terbang 34 menit.',
                'price' => 12999000,
                'stock' => 13,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Razer DeathAdder V3',
                'slug' => 'razer-deathadder-v3',
                'description' => 'Gaming mouse ergonomis dengan sensor Focus Pro 30K dan switch optik Razer.',
                'price' => 1299000,
                'stock' => 40,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Logitech MX Master 3S',
                'slug' => 'logitech-mx-master-3s',
                'description' => 'Mouse produktivitas dengan sensor 8K DPI, scroll MagSpeed, dan koneksi multi-device.',
                'price' => 1599000,
                'stock' => 28,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'SteelSeries Arctis 7P+',
                'slug' => 'steelseries-arctis-7p-plus',
                'description' => 'Gaming headset wireless dengan audio surround, mic ClearCast, dan baterai 30 jam.',
                'price' => 2799000,
                'stock' => 19,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mechanical Keyboard Keychron K8',
                'slug' => 'mechanical-keyboard-keychron-k8',
                'description' => 'Keyboard mekanik wireless dengan switch Gateron, backlight RGB, dan layout 87-key.',
                'price' => 1899000,
                'stock' => 24,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Webcam Logitech Brio 4K',
                'slug' => 'webcam-logitech-brio-4k',
                'description' => 'Webcam 4K Ultra HD dengan HDR, autofocus, dan field of view yang dapat disesuaikan.',
                'price' => 3299000,
                'stock' => 17,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Portable SSD Samsung T7',
                'slug' => 'portable-ssd-samsung-t7',
                'description' => 'SSD eksternal 1TB dengan kecepatan transfer hingga 1,050 MB/s dan enkripsi hardware.',
                'price' => 2199000,
                'stock' => 32,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Power Bank Anker PowerCore 26800',
                'slug' => 'power-bank-anker-powercore-26800',
                'description' => 'Power bank kapasitas besar 26800mAh dengan PowerIQ dan VoltageBoost technology.',
                'price' => 899000,
                'stock' => 45,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Monitor LG UltraWide 34WP65C',
                'slug' => 'monitor-lg-ultrawide-34wp65c',
                'description' => 'Monitor curved 34 inci dengan resolusi QHD, USB-C connectivity, dan color accuracy 99% sRGB.',
                'price' => 6999000,
                'stock' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]
        ];

        // Insert data ke database
        $this->db->table('products')->insertBatch($data);
    }
}